### ISSUE TITLE
Silent mode

### ISSUE THREAD

**Issue by mhnsn** [TGiles/auto-lighthouse#182]
**Is your feature request related to a problem? Please describe.**
I would like to be able to have a shorter output from the program for large websites. It's hard to track progress when there's a giant wall of report generations.

**Describe the solution you'd like**
Create a silent mode that doesn't tell when reports are generated, just that they're all done, and only tells the total number of endpoints to be tested.

**Describe alternatives you've considered**
Alternately, just update a tally of how many have been generated, i.e. `Created X/1492 reports`, and just show the total tally that has been pushed to test as `746 endpoints to test`.

**Comment by TGiles** [comment]
Hi mhnsn, thanks for filing this as well! Looking at the output of auto-lighthouse can be messy to say the least. I've wanted to implement a loading bar of sorts like npm, yarn, apt all use...but never got around to it. This is a valid feature request and something I'll implement in the near future! 

If you happen to know of any loading bar libraries for node, please let me know! Otherwise, I'll just go with the `Created X/Y reports`

**Comment by TGiles** [comment]
@mhnsn feel free to check out PR #185 and see if that PR fits your need. I think it will, but always want to make sure!
